version: '3.1'
services:
  # amqp container
  amqp:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - ./docker/20-logging.conf:/etc/rabbitmq/conf.d/20-logging.conf