package amqp.helper.protocol;

// This file was autogenerated by spec/GenerateDefinition.hx - Do not modify

class Constant {
  public static inline var FRAME_OVERHEAD:Int = 8;

  public static inline var FRAME_METHOD:Int = 1;
  public static inline var FRAME_HEADER:Int = 2;
  public static inline var FRAME_BODY:Int = 3;
  public static inline var FRAME_HEARTBEAT:Int = 8;
  public static inline var FRAME_MIN_SIZE:Int = 4096;
  public static inline var FRAME_END:Int = 206;
  public static inline var REPLY_SUCCESS:Int = 200;
  public static inline var CONTENT_TOO_LARGE:Int = 311;
  public static inline var NO_ROUTE:Int = 312;
  public static inline var NO_CONSUMERS:Int = 313;
  public static inline var ACCESS_REFUSED:Int = 403;
  public static inline var NOT_FOUND:Int = 404;
  public static inline var RESOURCE_LOCKED:Int = 405;
  public static inline var PRECONDITION_FAILED:Int = 406;
  public static inline var CONNECTION_FORCED:Int = 320;
  public static inline var INVALID_PATH:Int = 402;
  public static inline var FRAME_ERROR:Int = 501;
  public static inline var SYNTAX_ERROR:Int = 502;
  public static inline var COMMAND_INVALID:Int = 503;
  public static inline var CHANNEL_ERROR:Int = 504;
  public static inline var UNEXPECTED_FRAME:Int = 505;
  public static inline var RESOURCE_ERROR:Int = 506;
  public static inline var NOT_ALLOWED:Int = 530;
  public static inline var NOT_IMPLEMENTED:Int = 540;
  public static inline var INTERNAL_ERROR:Int = 541;
}
